# Jekyll
markdown: rdiscount
highlighter: pygments
permalink: /news/:year/:month/:day/:title
redcloth:
  hard_breaks: false
exclude:
  - LICENSE
  - notice.html
  - epl-v10.html
  - Gemfile
  - Gemfile.lock

# Custom
name: Golo news
description: "News about Golo, a lightweight dynamic language for the JVM."
url: http://golo-lang.org
