# Jekyll
highlighter: rouge
markdown: kramdown
permalink: /news/:year/:month/:day/:title
exclude:
  - LICENSE
  - notice.html
  - epl-v10.html
  - Gemfile
  - Gemfile.lock

# Custom
name: Golo news
description: "News about Golo, a lightweight dynamic language for the JVM."
url: http://golo-lang.org
