# Jekyll
markdown: rdiscount
pygments: true
permalink: /news/:year/:month/:day/:title
redcloth:
  hard_breaks: false

# Custom
name: Golo news
description: "News about Golo, a lightweight dynamic language for the JVM."
url: http://golo-lang.org
